# Generated by Django 3.0.2 on 2020-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20200202_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='doc',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
